site_name: iCrowds Documentation

theme:
  name: material

  palette:
    - scheme: default
      primary: grey
      accent: grey
      toggle:
        icon: material/weather-night
        name: Dark mode

    - scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/weather-sunny
        name: Light mode

nav:
  - Home: index.md

  - Static Systems:
      - Overview: static/index.md
      - Stadium: static/stadium.md
      - Scatter:
          - Ground Scatter: static/scatter/ground.md
          - Curve Scatter: static/scatter/curve.md
          - Vertex Scatter: static/scatter/vertex.md

  - Dynamic Systems:
      - Overview: dynamic/index.md
      - Ragdoll System: dynamic/ragdoll.md
      - Fluid System: dynamic/fluid.md
      - Walkers System: dynamic/walkers.md
      - City System: dynamic/city.md

  - Agents:
      - Customization: extra/agents.md

  - Help:
      - FAQ: extra/faq.md
      - Tutorials: extra/tutorials.md
